dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-1.0"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: c1db70f7106bd7011692030e88c8f2f3a2d2d023
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to review
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to review"
      deploy:
        provider: cloudfoundry
        api: https://api.sys.pikes.pal.pivotal.io
        username: itsmebinoy
        password: B@noyvp2@
        organization: binoy-valiya-parambath
        space: review
